### ISSUE TITLE
Nice Plugin but just I can press the doorbell

### ISSUE THREAD

**Issue by ghost** [TheDataLion/Doorbell#1]
The Doorbell work but one problem i create one but the bell trigger just me can activate the Bell sound other players nothing :(

**Comment by TheDataLioness** [comment]
I'm not be able to reproduce it. 
I also asked other players here on a server that has the plugin.
It seems to work fine here.

**Comment by ghost** [comment]
You have me not understand i write in german you translate then


Das plugin ist gut nur der klingelton kann nur vom ersteller abgespielt werden aber andere spieler wenn sie drauf drücken hören sie es nur aber selber wenn sie drauf drücken wird kein ton abgespielt das sollte man noch fixen

**Comment by TheDataLioness** [comment]
Ich habe es getestet.
Auch mit anderen Spielern und es scheint einfach richtig für mich zu funktionieren.
